# push.yml
# Name of workflow
name: Push workflow

# When workflow is triggered
on:
  push:
    branches:
      - dev
      - main

# Jobs to carry out
jobs:
  deploy:
    # Operating system to run job on
    runs-on: ubuntu-latest

    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v2

      # Install NodeJS
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      # Run npm install
      - name: Install Dependencies
        run: npm install

      # Run npm build
      - name: Build
        run: npm run build

      # Deploy to Netlify using production secrets
      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
